### ISSUE TITLE
Failed assertion using pygvt

### ISSUE THREAD

**Issue by ngoldbaum** [TACC/GraviT#8]
When I run `test.py` in the repo, using the latest version of the `dev` branch, I get the following output:

```
Create instance Cone0
Create instance Cube1
Create instance Cone2
Create instance Cube3
Create instance Cone4
Create instance Cube5
Create instance Cone6
Create instance Cube7
Create instance Cone8
Create instance Cone9
Create instance Cube10
Create instance Cone11
Create instance Cube12
Create instance Cone13
Create instance Cube14
Create instance Cone15
Create instance Cube16
Create instance Cone17
Create instance Cube18
Create instance Cone19
Create instance Cone20
Create instance Cube21
Create instance Cone22
Failed assertion `false [gvt/core/context/Database.cpp : 222]: Pointer used in marsh
```

This is happening in the call to `render`, here: https://github.com/TACC/GraviT/blob/4b20cd638dc35b9d0cd45b4dabb2d40e77462fcf/pygvt/test.py#L81

**Comment by hyungman** [comment]
Hi Nathan,

I'm having difficulty reproducing the problem. It could be an environment issue. Could you share a little more detail about your set-up? I particularly want to know various versions of the compiler and libraries (tbb, boost, mpi in particular) that you're using. We normally use Intel compilers for development. I tested pygvt using Intel compiler v17.0.4 and Python 3.6.2 on a Mac.

Hyungman

**Comment by ngoldbaum** [comment]
One big difference compared to your environment is that I'm using Apple's clang compiler since I don't have access to the intel compilers. I had to patch pygvt's setup.py to not look for the intel runtime libraries at build time and was planning to make a pull request once I get this issue resolved.

I have tbb 2018_U1, boost 1.65.1, and OpenMPI 2.1.2 installed under Python 3.6.2.

**Comment by ngoldbaum** [comment]
Oh and I should say that I'm able to run the C++ simple app and get an image, this error only happens under `pygvt`.

**Comment by hyungman** [comment]
Okay, I haven't tested it with Clang. I remember I had a few compilation errors using Clang on a Mac. Anyway, I'll try to use Clang and let you know. Hopefully I get the same assertion error as yours.

**Comment by ngoldbaum** [comment]
Yes, I ran into some compilation issues as well which @jgbarbosa fixed in 491c9875.

**Comment by hyungman** [comment]
Thanks for letting me know. I'm still getting errors though. Maybe that's because I'm using Apple LLVM 8. The fix seems to be for Apple LLVM 9.

**Comment by ngoldbaum** [comment]
On the `dev` branch?

**Comment by hyungman** [comment]
Yeah on the dev branch. on a Mac.

**Comment by hyungman** [comment]
Strange. I'm still not getting the assertion even after compiling the code using Apple Clang. I had to comment out irc and imf libraries in setup.py to work around linker errors. I forgot to pull the fix so I was getting compilation errors.

Here is my environment:

Apple LLVM version 8.0.0 (clang-800.0.42.1)
Python 3.6.2 |Anaconda custom (x86_64)
Cython version 0.25.2 (installed as part of conda)
tbb2017_20160916oss
Boost 1.64.0_1
open-mpi 1.10.2_1

**Comment by hyungman** [comment]
Can you perhaps clean, re-install, and try again? I once had some issue with Cython and removing the cached Cython build directory was helpful.

**Comment by hyungman** [comment]
I still haven't been able to reproduce the problem. The assertion error occurs while constructing the core context which in turns walks through the data base for initialization. I don't understand how some string (or key) other than bbox, mat, normi, and ptr got passed into that marsh function. This is the condition triggering the assertion. @jgbarbosa is currently working on one of the issues in the contexts. I wonder this problem has something to do with it.

**Comment by hyungman** [comment]
@jgbarbosa says the problem may only occur in MPI mode. Are you running it on multiple processes?

**Comment by ngoldbaum** [comment]
Hi sorry for responding slowly, I’m traveling right now. I will try to run under a debugger or with a printf to see what that string is.

**Comment by hyungman** [comment]
Nathan, Joao has reproduced the same assertion error on his Mac. He is going to fix it for us. Meanwhile, I'm going to check if I see the same problem on machines at TACC.

**Comment by ngoldbaum** [comment]
Did the fix ever end up getting generated? Happy to help out with debugging if you'd like.

**Comment by hyungman** [comment]
Sorry for the delay. Joao was looking into the issue. But he's currently traveling and should be in town tomorrow.

**Comment by hyungman** [comment]
Since I can't reproduce the problem here, can you temporarily remove the assertion and see if it runs?

**Comment by jgbarbosa** [comment]
Hi @ngoldbaum 

I have create a new branch called github-8, with a temporary fix. 
Please try it and let me know if it works.

**Comment by ngoldbaum** [comment]
Hmm, even after commenting out both of the asserts in `Database.cpp`, I'm still getting an assertion failure, almost as if it's somehow not including the latest version of gvt when i rebuild pygvt. I'm going to try rebuilding gvt completely from scratch to see if I can resolve that....

**Comment by jgbarbosa** [comment]
You need to compile and reinstall GVT.

Joao Barbosa
Visualization Group
Texas Advanced Computing Center
University of Texas at Austin

On Oct 18, 2017, at 1:59 PM, Nathan Goldbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, even after commenting out both of the asserts in Database.cpp, I'm still getting an assertion failure, almost as if it's somehow not including the latest version of gvt when i rebuild pygvt. I'm going to try rebuilding gvt completely from scratch to see if I can resolve that....

**Comment by ngoldbaum** [comment]
Right, I did recompile it from scratch (e.g. I did `make clean` - was that not sufficient?), still seeing that error. I'm now trying again from a fresh clone of the repository.

**Comment by jgbarbosa** [comment]
make install, you need to install. Most likely your pygvt is point to another location that it is not the build.


On Oct 18, 2017, at 2:04 PM, Nathan Goldbaum <notifications@github.com<mailto:notifications@github.com>> wrote:


Right, I did recompile it from scratch (e.g. I did make clean - was that not sufficient?), still seeing that error. I'm now trying again from a fresh clone of the repository.

**Comment by ngoldbaum** [comment]
Ah, you're right - I had a copy installed into `/usr/local`.

**Comment by ngoldbaum** [comment]
I can confirm that commenting out the asserts lets pygvt finish rendering. I end up with the following image:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/3126246/31738340-f289b1a2-b40f-11e7-89cc-e4175d7792fb.png">
